### ISSUE TITLE
/channel zu /kanal ändern

### ISSUE THREAD

**Issue by 2000Arion** [TanjunBot/Tanjun-Dokumentation#6]
**Beschreibe den Fehler**
@kollhdxdlp hat vor kurzem den Namen der `/channel` Commands zu `/kanal` geändert. In der Dokumentation wurde dies aber noch nicht geändert.

**Ort des Fehlers**
Wo hast du den Fehler gefunden? Bitte gib uns folgende Informationen:
1. Link zur Seite in der Dokumentation: https://tanjun.a2data.site/i/channel + Unterseiten
2. ~~(wenn möglich) Zeilenangaben des Fehlers~~
3. Screenshot(s) (+ Datum der Aufnahme wenn möglich): [img#1](https://img.arion2000.xyz/M5dg1psX6N.png) (26.08.2023 12:30 Uhr),  [img#2](https://img.arion2000.xyz/fvzcFC6a1D.png) (26.08.2023 12:32 Uhr) _+ weitere nicht genannte_

~~**(Falls zutreffend: Fehler reproduzieren)**~~
~~Was muss man tun, um den Fehler zu reproduzieren?~~

**Verbesserungsvorschlag**
Auch in der Dokumentation `/channel` zu `/kanal` ändern.

**Desktop (bitte vervollständige die folgenden Informationen):**
 - Betriebssystem: Windows
 - Browser: Opera GX
 - Version: 100.0.4815.82

~~**Smartphone (bitte vervollständige die folgenden Informationen):**~~
~~- Gerät: [z.B. iPhone6]~~
~~- Betriebssystem: [z.B. iOS8.1]~~
~~- Browser [z.B. stock browser, safari]~~
~~- Version [z.B. 22]~~

~~**Zusätzliche Informationen**~~
~~Hier ist Platz für weitere Informationen über das Problem.~~

**Comment by kollhdxdlp** [comment]
https://github.com/TanjunBot/Tanjun-Dokumentation/commit/73cb21b5de67b36a83990afef7013e56bbdfa137
